### PR TITLE
Task2

### PR DESCRIPTION
**Pull request by RuisuLee**
Task: https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task2-serve-spa-aws/task.md
**Manual deployment:**
S3-website: http://cake-bakery-app-manual.s3-website.eu-north-1.amazonaws.com/
CloudFront website: https://d3gbc14wafncaf.cloudfront.net/
**Auto deployment:**
S3-website: http://cake-bakery-app.s3-website-us-east-1.amazonaws.com
CloudFront website: https://d1lbue8aufr58b.cloudfront.net/

### CODE REVIEW

**Comment by ArtiFisher** [comment]
Are those links to manual or auto deployed app?
Could you also add missing links, since we have to add both of them?

**Comment by RuisuLee** [comment]
Thank you for your comment, @ArtiFisher
PR comment has been updated

**Comment by ArtiFisher** [comment]
Manual CloudFront link redirects me to https://cake-bakery-app-manual.s3.eu-north-1.amazonaws.com/index.html and shows XML with Access Denied Error. Try to check CloudFront settings, possibly it's configured wrong.

**Comment by ArtiFisher** [comment]
Now it's working, good job!
Also don't forget to think of store theme, if you haven't chosen it yet.

**Comment by azatdavliatshin** [comment]
Nice job!

**Review by azatdavliatshin — APPROVED** [review]

**Pull request merged**
